version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: my-laravel-vue-app
    container_name: laravel-vue
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:your_app_key_here
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=your_db
      - DB_USERNAME=your_user
      - DB_PASSWORD=your_pass
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_db
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
