version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-laravel
    container_name: laravel-app
    volumes:
      - .:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    depends_on:
      - db
    working_dir: /var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      # Xóa APP_KEY từ đây, chúng ta sẽ tạo nó sau
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=nick
      - DB_PASSWORD=123456
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_DRIVER=sync

  web:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: nick  
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: nick
      PMA_PASSWORD: 123456
    depends_on:
      - db
      
volumes:
  dbdata: