on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Setup .env
      run: |
        if [ ! -f .env ]; then
            cp .env.example .env
        else
            echo ".env file exists."
        fi
      shell: bash

    - name: Config Clearing
      run: php artisan config:clear

    - name: Cache Clearing
      run: php artisan cache:clear

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        server-dir: /tdkt.kesug.com/htdocs/tdkt/